application: dash-live-streams
version: 1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css
  expiration: 1h
- url: /js
  static_dir: static/js
  expiration: 1h
- url: /img
  static_dir: static/img
  expiration: 30d
- url: /fonts
  static_dir: static/fonts
  expiration: 365d
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto  
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.less
- ^(.*/)?.*\.bat
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^console.py
- ^bulkloader-.*
- ^backups
- ^fixtures
- ^media
- ^\.git.*
- ^\.gaedata
- ^.*\.txt
- ^.*\.mp4
- ^README.md
